name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # runs every day at midnight
  workflow_dispatch:     # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate the snake files in './dist'
        uses: Platane/snk@v3
        with:
          github_user_name: rezaulrht
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push snake files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
